### PR TITLE
Build debian package using Github Actions

### PR DESCRIPTION
**Pull request by gwilherm**
Build debian package using Github Actions

1st commit:
Added a Github Action to build a debian package :
- The job is triggered when a release is published
- Checkouts the source code at the release tag
- Build the app
- Build the package
- Upload the package to the release files

2nd commit:
- Convert the markdown doc to HTML doc with pandoc

### CODE REVIEW

**Comment by David-Else** [comment]
Can we have a `.deb` version in the near future, if not a flatpak? Installing from source is not something most people would be able to, or want to do. THANKS!

**Comment by gwilherm** [comment]
Hello David, an up-to-date `.deb` is available here : https://github.com/gwilherm/alsa-scarlett-gui-debian-package/releases/tag/0.2-18-ga2bb

**Comment by David-Else** [comment]
@gwilherm Thanks!

**Comment by David-Else** [comment]
@gwilherm It seems to work great on Debian 12, awesome! 

I did get an ominous error `Download is performed unsandboxed as root as file` at the end of the installation, do you what it could mean?
```sh
sudo apt install ./alsa-scarlett-gui_0.2-18-ga2bb_amd64.deb 
[sudo] password for david: 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'alsa-scarlett-gui' instead of './alsa-scarlett-gui_0.2-18-ga2bb_amd64.deb'
The following NEW packages will be installed:
  alsa-scarlett-gui
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/3,180 kB of archives.
After this operation, 4,413 kB of additional disk space will be used.
Get:1 /home/david/Downloads/alsa-scarlett-gui_0.2-18-ga2bb_amd64.deb alsa-scarlett-gui amd64 0.2-18-ga2bb [3,180 kB]
Selecting previously unselected package alsa-scarlett-gui.
(Reading database ... 212755 files and directories currently installed.)
Preparing to unpack .../alsa-scarlett-gui_0.2-18-ga2bb_amd64.deb ...
Unpacking alsa-scarlett-gui (0.2-18-ga2bb) ...
Setting up alsa-scarlett-gui (0.2-18-ga2bb) ...
Processing triggers for desktop-file-utils (0.26-1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for gnome-menus (3.36.0-1.1) ...
Processing triggers for mailcap (3.70+nmu1) ...
N: Download is performed unsandboxed as root as file '/home/david/Downloads/alsa-scarlett-gui_0.2-18-ga2bb_amd64.deb' couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)
```

**Comment by David-Else** [comment]
I am also getting a crash on trying to save:

image

I have `alsactl` installed:

```sh
apt search alsactl
Sorting... Done
Full Text Search... Done
alsa-utils/stable,now 1.2.8-1 amd64 [installed,automatic]
  Utilities for configuring and using ALSA
```

**Comment by gwilherm** [comment]
> @gwilherm 

> I did get an ominous error `Download is performed unsandboxed as root as file` at the end of the installation, do you know what it could mean?`

I use the following command to install (on Ubuntu) and I have no such error :
```
sudo dpkg -i ./alsa-scarlett-gui_0.2-18-ga2bb_amd64.deb
```

The warning seems to be caused by the fact the user `_apt` can not access to your home directory, so apt uses the `root` user to access the file.

**Comment by gwilherm** [comment]
@David-Else 
> I am also getting a crash on trying to save configuration:
> 
> image
> 
> I have `alsactl` installed:
> 
> ```shell
> apt search alsactl
> Sorting... Done
> Full Text Search... Done
> alsa-utils/stable,now 1.2.8-1 amd64 [installed,automatic]
>   Utilities for configuring and using ALSA
> ```

I don't have the issue on Ubuntu 22.4.
I tried on a Debian 12 VM without using the `.deb`, but compiling and installing from sources (make -j4 ; make install), I confirm the issue and it's not related to my packaging. I am openning a new issue.
On Debian alsactl is installed in `/usr/sbin` and can only be executed by `root` user.

**Comment by David-Else** [comment]
@gwilherm Thanks for your help with this! I hope that @geoffreybennett merges this and enables the `.deb` file building as it will help many users.

**Comment by gwilherm** [comment]
@David-Else here a workaround:
In a terminal execute the command that failed with sudo:
```
sudo alsactl store hw:1 -f ~/scarlett-config.state
```

Then you will need to give you the property of the file because it will be owned by `root:root`
```
sudo chown $(id -un):$(id -gn) ~/scarlett-config.state
```

**Comment by David-Else** [comment]
I tried your suggestion and get the same error.

**Comment by gwilherm** [comment]
> I tried your suggestion and get the same error.

Maybe because I misspelled the command ? it is `sbin`
```
export PATH=${PATH}:/usr/sbin
```

**Comment by David-Else** [comment]
Thanks, works now!

**Comment by geoffreybennett** [comment]
Hi! Thanks for the poke David. I think the "Generate the documentation" deb step should probably be in the Makefile instead as that would be useful for the RPM as well? "make doc"?

**Comment by gwilherm** [comment]
Yes it could be a part of the Makefile, I just didn't want to be too intrusive, especially adding a dependency (even if it is an optional dependency)

**Comment by tjaalton** [comment]
Would it be useful to get the app in Debian/Ubuntu? I'm a DD (and ubuntu core-dev), so I could upload and maintain it there. Just bought a 4th gen 2i2 myself :)

**Comment by geoffreybennett** [comment]
@gwilherm Wow, looks like it worked?
@tjaalton I wouldn't mind. Please discuss with Dale: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1036223

**Comment by sporksnail** [comment]
Hi @tjaalton, @gwilherm - I'm Dale from the BTS. I picked up the RFP before I'd seen this conversation. I'm not a DD (or even a DM) so I'm happy to hand this over if someone more experienced wants to take it on. I've already done some work on the packaging, so please let me know if I can contribute in some way.

**Comment by gwilherm** [comment]
> @gwilherm Wow, looks like it worked?
Looks like yes :smile:
I tried to install both on my xubuntu 22.04 the app is functional but there are minor bugs:
- .deb: no icon in the desktop launcher (menu XFCE for me) : I think it's because we renamed it when we merged works for flatpak
image

- .flatpak: About window does not show the version (I think I just forgot to do it in the Github workflow with git describe)
image

I'll try to fix that in the week (maybe tomorrow)

**Comment by sporksnail** [comment]
My Debian packaging WIP is here, if any of it is useful:
[https://github.com/sporksnail/alsa-scarlett-gui/tree/debian/latest](https://github.com/sporksnail/alsa-scarlett-gui/tree/debian/latest)

**Comment by sporksnail** [comment]
I've created a Debian packaging repo here, and the first release (0.3.2-1) is ready to go:
https://salsa.debian.org/doge-tech/alsa-scarlett-gui

@tjaalton - I've not yet requested a sponsor to upload this package. Since you're a DD and you've shown interest in this package, would you be willing to sponsor it for me?

**Comment by tjaalton** [comment]
@sporksnail sure thing, should I use that project for issues in the packaging? :)

**Comment by sporksnail** [comment]
@tjaalton - Fantastic, thank you! Yes, please feel free to raise any issues in the Salsa project.

**Pull request closed without merging**
