### PR TITLE
Add information on how to convert RPM releases into DEB packages

### PR DESCRIPTION
**Pull request by Dragunovam**
Nothing much, thought it'd be handy for novice Linux users to be able to convert the package into a deb file instead of having to build it from source.

### CODE REVIEW

**Comment by sebakami** [comment]
It looks like the information is added twice in different places.

Although the information is useful, I doubt that USAGE.md is the right place for it. The document is (currently) aimed at users compiling the software from source. After all, creating the rpm package is also not covered in this document.

Should the user be in charge for creating the deb package? If so, it is not described where to get the rpm file from. Is it available from somewhere?

**Comment by geoffreybennett** [comment]
This is the wrong solution. Correct solution would be for us to create the .deb as part of the binary release. If someone wants to look at this, I found: https://wiki.debian.org/Packaging/Intro

**Comment by Dragunovam** [comment]
> It looks like the information is added twice in different places.
> 
> Although the information is useful, I doubt that USAGE.md is the right place for it. The document is (currently) aimed at users compiling the software from source. After all, creating the rpm package is also not covered in this document.
> 
> Should the user be in charge for creating the deb package? If so, it is not described where to get the rpm file from. Is it available from somewhere?

You're absolutely correct, I added the text but later found out the information about deb packages was not in the correct location in the USAGE.md. Afterwards I changed the file to show the relevant text in a less-awkward position but forgot to undo the first commit. @geoffreybennett was kind enough to include an RPM in the latest test release, but was unable to easily create a DEB package so I thought the option to add easy instructions to achieve this could be very useful. 

Alien converts the package correctly, I verified the output and -except some metadata added by alien to show it's a converted package- the deb package matches the original source. If future releases include a compiled or converted DEB package, these instructions become irrelevant.

I simply want every Linux user with a scarlett device to be able to use this tool. It's awesome.

**Comment by geoffreybennett** [comment]
See #23.

**Pull request closed without merging**
