### PR TITLE
Build flatpak package using Github Actions

### PR DESCRIPTION
**Pull request by gwilherm**
Proposition for issue #32, feel free to review/comment it

In the vein of PR #23 here is a Github Actions script to build a flatpak package.
It is based on @aledomu's work (PR #41) and is triggered on release action.

### CODE REVIEW

**Comment by geoffreybennett** [comment]
Hi @gwilherm @aledomu, sorry for the delay here. I hadn't looked under the pull requests tab in github for a long time.

I did a rebase/squash fixups and pushed to the flatpak branch for you to check. I'm not sure what to do with the commit "Fix Error: icon alsa-scarlett-gui not found below...". The comment says it's needed, but the commit removes it. I don't understand anything flatpak, so I'm not sure what to do with this?

**Comment by gwilherm** [comment]
Hi @geoffreybennett no worries :)

In the documentation they says to use "rename-icon" if it is not possible to rename the file itself, (I guess for instance if the packager do not own the "upstream" code repository)
https://docs.flatpak.org/en/latest/manifests.html#file-renaming
But @aledomu renamed the icon in place ([b5ca1b2](https://github.com/geoffreybennett/alsa-scarlett-gui/pull/66/commits/b5ca1b258ef23c384f18e0c8f37bd4525b8d2059)), I think it is an omission, the file can not be renamed twice.

**Comment by geoffreybennett** [comment]
Ok, understood, thanks.

FYI your git user info is showing in the commits as "Guillaume <1017720+gwilherm@users.noreply.github.com>". Do you want to keep it that way?

**Comment by geoffreybennett** [comment]
Rather than commenting out, I think better to just delete?
```
-rename-icon: alsa-scarlett-gui
+# rename-icon: alsa-scarlett-gui
```

Do you know what this comment refers to?
```
# If publishing to Flathub, this option is required for version (tag) 0.2
```
I thought that was referring to the `rename-icon` line which is part of why I was confused. If it was, then delete that comment too?

**Comment by gwilherm** [comment]
Hi,
> I thought that was referring to the rename-icon line which is part of why I was confused. If it was, then delete that comment too?
TBH I also was confused by this comment, maybe @aledomu could enlighten us ?

> FYI your git user info is showing in the commits as "Guillaume [1017720+gwilherm@users.noreply.github.com](mailto:1017720+gwilherm@users.noreply.github.com)". Do you want to keep it that way?
Yep, I am not fan of email

**Comment by geoffreybennett** [comment]
I have added those to master now. Does that look right?

**Comment by geoffreybennett** [comment]
What happens now? In https://github.com/geoffreybennett/alsa-scarlett-gui/actions it says "There are no workflow runs yet."

Is there some way to test besides making a release?

**Comment by gwilherm** [comment]
No, the only way to test this particular script is to make a release with a new tag through Github interface.
Se the begin of the script
```
on:
  release:
    branches: '*'
    types: [published]
```
The Github Action CI is triggered on the release event and the app is built and packaged on the Github servers.
The release can be deleted afterward if not desired.

If you want to be able to trigger it by hand, it should use `workflow_dispatch`, for example:

```
name: Build flatpak package (latest)

on:  workflow_dispatch

env:
  APP_NAME:    alsa-scarlett-gui

jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-45
      options: --privileged
    steps:
    - uses: actions/checkout@v4

    - name: Build flatpak package
      uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: ${{ env.APP_NAME }}.flatpak
        manifest-path: vu.b4.alsa-scarlett-gui.yml
        cache-key: flatpak-builder-${{ github.sha }}
```

This workflows has a button "Run workflow"
image

I removed the parts related to release because they do not make sense in a "workflow_dispatch"
Here the flatpak file will be added into a zip and attached to the "workflow run" in "Action" tab (ex: https://github.com/gwilherm/alsa-scarlett-gui/actions/runs/6588361316). But here artifacts are available only for 90 days. Releases attachments are permanent.

**Comment by aledomu** [comment]
The reason for this comment (now deleted):

```
# If publishing to Flathub, this option is required for version (tag) 0.2
# rename-icon: alsa-scarlett-gui
```

Lies in the end of the manifest:

```
# Use the following and remove the above for Flathub publishing
# - type: git
#   url: https://github.com/geoffreybennett/alsa-scarlett-gui.git
#   tag: "0.2"
```

Unless you make a new release before submitting a request to Flathub to publish this app, the change of name of the icon file will not appear in the last git tag release, which right now is `0.2`. That is why you need to uncomment the `rename-icon` setting in that case.

**Pull request closed without merging**
